name: CI

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  SetUpEnvironment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./

  dockerApplicationSetUp:
    runs-on: ubuntu-latest
    steps:
    - name : Pull docker image
      run: docker pull gprestes/the-internet
    - name: Run docker image
      run: docker run -d -p 7080:5000 gprestes/the-internet

  webBrowserSystemTests:
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
        web-browser: [GoogleChrome, MicrosoftEdge]
    needs: [SetUpEnvironment, dockerApplicationSetUp]
    runs-on: ${{ matrix.operating-system }}
    env:
      WebBrowser: ${{ matrix.web-browser }}
    steps:
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./
    - name: Create logs folder
      if: matrix.operating-system == 'ubuntu-latest'
      run: |
        mkdir ./TheInternetApp/bin/Debug/net6.0/logs
        ls ./TheInternetApp/bin/Debug/net6.0/    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      timeout-minutes: 15
    - name: Upload logs from System tests
      uses: actions/upload-artifact@v3
      with:
        name: system-tests-logs
        path: ./TheInternetApp/bin/Debug/net6.0/logs/
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-${{ matrix.operating-system }}-${{ matrix.web-browser }}
        path: ${{ github.workspace }} 

  webBrowserUiTests:
    runs-on: ubuntu-latest
    needs: SetUpEnvironment
    steps:
    - name : Pull docker image
      run: docker pull gprestes/the-internet
    - name: Run docker image
      run: docker run -d -p 7080:5000 gprestes/the-internet
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 17.9.0
    - name: Setup testcafe environment
      uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome:headless ./TheInternetApp/UiTests/Tests"
